"""add_plan_is_binding

Revision ID: 086e2b8888c4
Revises: b08a5ba1f4ff
Create Date: 2026-04-12 13:03:32.282160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '086e2b8888c4'
down_revision: Union[str, Sequence[str], None] = 'b08a5ba1f4ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('is_binding', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.create_index('uq_plan_one_binding_per_period', 'plan', ['plan_period_id'], unique=True, postgresql_where=sa.text('is_binding = TRUE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_plan_one_binding_per_period', table_name='plan', postgresql_where=sa.text('is_binding = TRUE'))
    op.drop_column('plan', 'is_binding')
    # ### end Alembic commands ###
