"""initial schema

Revision ID: 163d3b2a85cc
Revises: 
Create Date: 2026-03-14 21:09:51.870491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '163d3b2a85cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('excel_export_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('color_head_weekdays_1', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('color_head_weekdays_2', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('color_head_locations_1', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('color_head_locations_2', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('color_day_nrs_1', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('color_day_nrs_2', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('color_column_kw_1', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('color_column_kw_2', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('excel_export_settings_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['excel_export_settings_id'], ['excel_export_settings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('address',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('street', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('prep_delete', sa.DateTime(timezone=True), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cast_rule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('rule', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('prep_delete', sa.DateTime(timezone=True), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('employee_event_category',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('prep_delete', sa.DateTime(timezone=True), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('flag',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('prep_delete', sa.DateTime(timezone=True), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'project_id')
    )
    op.create_table('skill',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('prep_delete', sa.DateTime(timezone=True), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'project_id')
    )
    op.create_table('time_of_day_enum',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('abbreviation', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('time_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('prep_delete', sa.DateTime(timezone=True), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('project_standard_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_standard_id'], ['project.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbreviation', 'project_id'),
    sa.UniqueConstraint('name', 'project_id'),
    sa.UniqueConstraint('time_index', 'project_id')
    )
    op.create_table('employee_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('google_calendar_event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('prep_delete', sa.DateTime(timezone=True), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('address_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location_of_work',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nr_actors', sa.Integer(), nullable=False),
    sa.Column('fixed_cast', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fixed_cast_only_if_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('prep_delete', sa.DateTime(timezone=True), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('address_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name')
    )
    op.create_table('person',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('f_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('l_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('gender', sa.Enum('female', 'male', 'divers', name='gender'), nullable=True),
    sa.Column('role', sa.Enum('SUPERVISOR', 'ADMIN', 'DISPATCHER', 'EMPLOYEE', 'APPRENTICE', 'GUEST', name='role'), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('phone_nr', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('requested_assignments', sa.Integer(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('prep_delete', sa.DateTime(timezone=True), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('admin_of_project_id', sa.Uuid(), nullable=True),
    sa.Column('address_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['admin_of_project_id'], ['project.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('f_name', 'l_name', 'project_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('time_of_day',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('start', sa.Time(), nullable=False),
    sa.Column('end', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('prep_delete', sa.DateTime(timezone=True), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('project_defaults_id', sa.Uuid(), nullable=True),
    sa.Column('project_standard_id', sa.Uuid(), nullable=True),
    sa.Column('time_of_day_enum_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_defaults_id'], ['project.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_standard_id'], ['project.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['time_of_day_enum_id'], ['time_of_day_enum.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actor_location_pref',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('prep_delete', sa.DateTime(timezone=True), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('location_of_work_id', sa.Uuid(), nullable=False),
    sa.Column('person_default_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['location_of_work_id'], ['location_of_work.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_default_id'], ['person.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actor_partner_location_pref',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('prep_delete', sa.DateTime(timezone=True), nullable=True),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('partner_id', sa.Uuid(), nullable=False),
    sa.Column('location_of_work_id', sa.Uuid(), nullable=False),
    sa.Column('person_default_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['location_of_work_id'], ['location_of_work.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partner_id'], ['person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_default_id'], ['person.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_event_category_link',
    sa.Column('employee_event_id', sa.Uuid(), nullable=False),
    sa.Column('employee_event_category_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['employee_event_category_id'], ['employee_event_category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_event_id'], ['employee_event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('employee_event_id', 'employee_event_category_id')
    )
    op.create_table('location_of_work_time_of_day',
    sa.Column('location_of_work_id', sa.Uuid(), nullable=False),
    sa.Column('time_of_day_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['location_of_work_id'], ['location_of_work.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['time_of_day_id'], ['time_of_day.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_of_work_id', 'time_of_day_id')
    )
    op.create_table('location_of_work_time_of_day_std',
    sa.Column('location_of_work_id', sa.Uuid(), nullable=False),
    sa.Column('time_of_day_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['location_of_work_id'], ['location_of_work.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['time_of_day_id'], ['time_of_day.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_of_work_id', 'time_of_day_id')
    )
    op.create_table('person_employee_event',
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('employee_event_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['employee_event_id'], ['employee_event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('person_id', 'employee_event_id')
    )
    op.create_table('person_flag',
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('flag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['flag_id'], ['flag.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('person_id', 'flag_id')
    )
    op.create_table('person_skill',
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('person_id', 'skill_id')
    )
    op.create_table('person_time_of_day',
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('time_of_day_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['time_of_day_id'], ['time_of_day.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('person_id', 'time_of_day_id')
    )
    op.create_table('person_time_of_day_standard',
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('time_of_day_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['time_of_day_id'], ['time_of_day.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('person_id', 'time_of_day_id')
    )
    op.create_table('skill_group',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nr_actors', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('prep_delete', sa.DateTime(timezone=True), nullable=True),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('location_of_work_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['location_of_work_id'], ['location_of_work.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('prep_delete', sa.DateTime(timezone=True), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('dispatcher_id', sa.Uuid(), nullable=True),
    sa.Column('excel_export_settings_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['dispatcher_id'], ['person.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['excel_export_settings_id'], ['excel_export_settings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name')
    )
    op.create_table('combination_locations_possible',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('time_span_between', sa.Interval(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('prep_delete', sa.DateTime(timezone=True), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_period',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('start', sa.Date(), nullable=False),
    sa.Column('end', sa.Date(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes_for_employees', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.Column('remainder', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('prep_delete', sa.DateTime(timezone=True), nullable=True),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_actor_assign',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('start', sa.Date(), nullable=False),
    sa.Column('end', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_employee_event',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('employee_event_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['employee_event_id'], ['employee_event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'employee_event_id')
    )
    op.create_table('team_location_assign',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('start', sa.Date(), nullable=False),
    sa.Column('end', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('location_of_work_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['location_of_work_id'], ['location_of_work.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actor_plan_period',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('requested_assignments', sa.Integer(), nullable=False),
    sa.Column('required_assignments', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('plan_period_id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_period_id'], ['plan_period.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cast_group',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fixed_cast', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fixed_cast_only_if_available', sa.Boolean(), nullable=False),
    sa.Column('prefer_fixed_cast_events', sa.Boolean(), nullable=False),
    sa.Column('nr_actors', sa.Integer(), nullable=False),
    sa.Column('custom_rule', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('strict_cast_pref', sa.Integer(), nullable=False),
    sa.Column('plan_period_id', sa.Uuid(), nullable=False),
    sa.Column('cast_rule_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['cast_rule_id'], ['cast_rule.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_period_id'], ['plan_period.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location_of_work_combination_loc',
    sa.Column('location_of_work_id', sa.Uuid(), nullable=False),
    sa.Column('combination_locations_possible_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['combination_locations_possible_id'], ['combination_locations_possible.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_of_work_id'], ['location_of_work.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_of_work_id', 'combination_locations_possible_id')
    )
    op.create_table('location_plan_period',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nr_actors', sa.Integer(), nullable=True),
    sa.Column('fixed_cast', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fixed_cast_only_if_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('plan_period_id', sa.Uuid(), nullable=False),
    sa.Column('location_of_work_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['location_of_work_id'], ['location_of_work.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_period_id'], ['plan_period.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person_combination_loc',
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('combination_locations_possible_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['combination_locations_possible_id'], ['combination_locations_possible.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('person_id', 'combination_locations_possible_id')
    )
    op.create_table('plan',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location_columns', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('prep_delete', sa.DateTime(timezone=True), nullable=True),
    sa.Column('plan_period_id', sa.Uuid(), nullable=False),
    sa.Column('excel_export_settings_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['excel_export_settings_id'], ['excel_export_settings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_period_id'], ['plan_period.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'plan_period_id')
    )
    op.create_table('actor_plan_period_combination_loc',
    sa.Column('actor_plan_period_id', sa.Uuid(), nullable=False),
    sa.Column('combination_locations_possible_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_plan_period_id'], ['actor_plan_period.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['combination_locations_possible_id'], ['combination_locations_possible.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('actor_plan_period_id', 'combination_locations_possible_id')
    )
    op.create_table('actor_plan_period_loc_pref',
    sa.Column('actor_plan_period_id', sa.Uuid(), nullable=False),
    sa.Column('actor_location_pref_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_location_pref_id'], ['actor_location_pref.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['actor_plan_period_id'], ['actor_plan_period.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('actor_plan_period_id', 'actor_location_pref_id')
    )
    op.create_table('actor_plan_period_partner_pref',
    sa.Column('actor_plan_period_id', sa.Uuid(), nullable=False),
    sa.Column('actor_partner_location_pref_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_partner_location_pref_id'], ['actor_partner_location_pref.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['actor_plan_period_id'], ['actor_plan_period.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('actor_plan_period_id', 'actor_partner_location_pref_id')
    )
    op.create_table('actor_plan_period_time_of_day',
    sa.Column('actor_plan_period_id', sa.Uuid(), nullable=False),
    sa.Column('time_of_day_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_plan_period_id'], ['actor_plan_period.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['time_of_day_id'], ['time_of_day.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('actor_plan_period_id', 'time_of_day_id')
    )
    op.create_table('actor_plan_period_time_of_day_std',
    sa.Column('actor_plan_period_id', sa.Uuid(), nullable=False),
    sa.Column('time_of_day_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_plan_period_id'], ['actor_plan_period.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['time_of_day_id'], ['time_of_day.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('actor_plan_period_id', 'time_of_day_id')
    )
    op.create_table('avail_day_group',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nr_avail_day_groups', sa.Integer(), nullable=True),
    sa.Column('variation_weight', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actor_plan_period_id', sa.Uuid(), nullable=True),
    sa.Column('avail_day_group_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['actor_plan_period_id'], ['actor_plan_period.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['avail_day_group_id'], ['avail_day_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cast_group_link',
    sa.Column('parent_id', sa.Uuid(), nullable=False),
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['cast_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['cast_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_id', 'child_id')
    )
    op.create_table('event_group',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nr_event_groups', sa.Integer(), nullable=True),
    sa.Column('variation_weight', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location_plan_period_id', sa.Uuid(), nullable=True),
    sa.Column('event_group_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['event_group_id'], ['event_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_plan_period_id'], ['location_plan_period.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location_plan_period_time_of_day',
    sa.Column('location_plan_period_id', sa.Uuid(), nullable=False),
    sa.Column('time_of_day_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['location_plan_period_id'], ['location_plan_period.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['time_of_day_id'], ['time_of_day.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_plan_period_id', 'time_of_day_id')
    )
    op.create_table('location_plan_period_time_of_day_std',
    sa.Column('location_plan_period_id', sa.Uuid(), nullable=False),
    sa.Column('time_of_day_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['location_plan_period_id'], ['location_plan_period.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['time_of_day_id'], ['time_of_day.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_plan_period_id', 'time_of_day_id')
    )
    op.create_table('max_fair_shifts_of_app',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('max_shifts', sa.Integer(), nullable=False),
    sa.Column('fair_shifts', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actor_plan_period_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_plan_period_id'], ['actor_plan_period.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avail_day',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('prep_delete', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actor_plan_period_id', sa.Uuid(), nullable=False),
    sa.Column('avail_day_group_id', sa.Uuid(), nullable=False),
    sa.Column('time_of_day_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_plan_period_id'], ['actor_plan_period.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['avail_day_group_id'], ['avail_day_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['time_of_day_id'], ['time_of_day.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actor_plan_period_id', 'date', 'time_of_day_id')
    )
    op.create_table('event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('prep_delete', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_of_day_id', sa.Uuid(), nullable=False),
    sa.Column('event_group_id', sa.Uuid(), nullable=False),
    sa.Column('cast_group_id', sa.Uuid(), nullable=False),
    sa.Column('location_plan_period_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['cast_group_id'], ['cast_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_group_id'], ['event_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_plan_period_id'], ['location_plan_period.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['time_of_day_id'], ['time_of_day.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('required_avail_day_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('num_avail_day_groups', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('avail_day_group_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['avail_day_group_id'], ['avail_day_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('guests', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('prep_delete', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avail_day_combination_loc',
    sa.Column('avail_day_id', sa.Uuid(), nullable=False),
    sa.Column('combination_locations_possible_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['avail_day_id'], ['avail_day.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['combination_locations_possible_id'], ['combination_locations_possible.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('avail_day_id', 'combination_locations_possible_id')
    )
    op.create_table('avail_day_loc_pref',
    sa.Column('avail_day_id', sa.Uuid(), nullable=False),
    sa.Column('actor_location_pref_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_location_pref_id'], ['actor_location_pref.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['avail_day_id'], ['avail_day.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('avail_day_id', 'actor_location_pref_id')
    )
    op.create_table('avail_day_partner_pref',
    sa.Column('avail_day_id', sa.Uuid(), nullable=False),
    sa.Column('actor_partner_location_pref_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_partner_location_pref_id'], ['actor_partner_location_pref.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['avail_day_id'], ['avail_day.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('avail_day_id', 'actor_partner_location_pref_id')
    )
    op.create_table('avail_day_skill',
    sa.Column('avail_day_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['avail_day_id'], ['avail_day.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('avail_day_id', 'skill_id')
    )
    op.create_table('avail_day_time_of_day',
    sa.Column('avail_day_id', sa.Uuid(), nullable=False),
    sa.Column('time_of_day_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['avail_day_id'], ['avail_day.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['time_of_day_id'], ['time_of_day.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('avail_day_id', 'time_of_day_id')
    )
    op.create_table('event_flag',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('flag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['flag_id'], ['flag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'flag_id')
    )
    op.create_table('event_skill_group',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('skill_group_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_group_id'], ['skill_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'skill_group_id')
    )
    op.create_table('event_time_of_day',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('time_of_day_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['time_of_day_id'], ['time_of_day.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'time_of_day_id')
    )
    op.create_table('location_of_work_req_avail_day_groups',
    sa.Column('location_of_work_id', sa.Uuid(), nullable=False),
    sa.Column('required_avail_day_groups_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['location_of_work_id'], ['location_of_work.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['required_avail_day_groups_id'], ['required_avail_day_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_of_work_id', 'required_avail_day_groups_id')
    )
    op.create_table('avail_day_appointment',
    sa.Column('avail_day_id', sa.Uuid(), nullable=False),
    sa.Column('appointment_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['avail_day_id'], ['avail_day.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('avail_day_id', 'appointment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avail_day_appointment')
    op.drop_table('location_of_work_req_avail_day_groups')
    op.drop_table('event_time_of_day')
    op.drop_table('event_skill_group')
    op.drop_table('event_flag')
    op.drop_table('avail_day_time_of_day')
    op.drop_table('avail_day_skill')
    op.drop_table('avail_day_partner_pref')
    op.drop_table('avail_day_loc_pref')
    op.drop_table('avail_day_combination_loc')
    op.drop_table('appointment')
    op.drop_table('required_avail_day_groups')
    op.drop_table('event')
    op.drop_table('avail_day')
    op.drop_table('max_fair_shifts_of_app')
    op.drop_table('location_plan_period_time_of_day_std')
    op.drop_table('location_plan_period_time_of_day')
    op.drop_table('event_group')
    op.drop_table('cast_group_link')
    op.drop_table('avail_day_group')
    op.drop_table('actor_plan_period_time_of_day_std')
    op.drop_table('actor_plan_period_time_of_day')
    op.drop_table('actor_plan_period_partner_pref')
    op.drop_table('actor_plan_period_loc_pref')
    op.drop_table('actor_plan_period_combination_loc')
    op.drop_table('plan')
    op.drop_table('person_combination_loc')
    op.drop_table('location_plan_period')
    op.drop_table('location_of_work_combination_loc')
    op.drop_table('cast_group')
    op.drop_table('actor_plan_period')
    op.drop_table('team_location_assign')
    op.drop_table('team_employee_event')
    op.drop_table('team_actor_assign')
    op.drop_table('plan_period')
    op.drop_table('combination_locations_possible')
    op.drop_table('team')
    op.drop_table('skill_group')
    op.drop_table('person_time_of_day_standard')
    op.drop_table('person_time_of_day')
    op.drop_table('person_skill')
    op.drop_table('person_flag')
    op.drop_table('person_employee_event')
    op.drop_table('location_of_work_time_of_day_std')
    op.drop_table('location_of_work_time_of_day')
    op.drop_table('employee_event_category_link')
    op.drop_table('actor_partner_location_pref')
    op.drop_table('actor_location_pref')
    op.drop_table('time_of_day')
    op.drop_table('person')
    op.drop_table('location_of_work')
    op.drop_table('employee_event')
    op.drop_table('time_of_day_enum')
    op.drop_table('skill')
    op.drop_table('flag')
    op.drop_table('employee_event_category')
    op.drop_table('cast_rule')
    op.drop_table('address')
    op.drop_table('project')
    op.drop_table('excel_export_settings')
    # ### end Alembic commands ###
