"""add_email_settings_table

Revision ID: 4e3571332c12
Revises: f9a8b7c6d5e4
Create Date: 2026-05-01 00:01:33.369564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4e3571332c12'
down_revision: Union[str, Sequence[str], None] = 'f9a8b7c6d5e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('smtp_host', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.Column('smtp_username', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('smtp_password_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('use_tls', sa.Boolean(), nullable=False),
    sa.Column('use_ssl', sa.Boolean(), nullable=False),
    sa.Column('email_from', sqlmodel.sql.sqltypes.AutoString(length=254), nullable=False),
    sa.Column('email_from_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('last_send_succeeded_at', sa.DateTime(), nullable=True),
    sa.Column('last_send_failed_at', sa.DateTime(), nullable=True),
    sa.Column('last_send_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['web_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_settings')
    # ### end Alembic commands ###
