"""add_cancellation_workflow

Revision ID: 6e9afef81aa1
Revises: 086e2b8888c4
Create Date: 2026-04-13 15:54:02.083507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6e9afef81aa1'
down_revision: Union[str, Sequence[str], None] = '086e2b8888c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('cancellation_deadline_hours', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('inbox_message',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recipient_web_user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('cancellation_new', 'cancellation_withdrawn', 'cancellation_resolved', 'takeover_offer_received', 'takeover_accepted', 'swap_request_received', 'swap_accepted_by_target', 'swap_confirmed', 'swap_rejected', name='inboxmessagetype'), nullable=False),
    sa.Column('reference_id', sa.Uuid(), nullable=False),
    sa.Column('reference_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('snapshot_data', sa.JSON(), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['recipient_web_user_id'], ['web_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location_notification_circle',
    sa.Column('location_of_work_id', sa.Uuid(), nullable=False),
    sa.Column('web_user_id', sa.Uuid(), nullable=False),
    sa.Column('added_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['web_user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_of_work_id'], ['location_of_work.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['web_user_id'], ['web_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_of_work_id', 'web_user_id')
    )
    op.create_table('team_notification_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('cancellation_deadline_hours', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id')
    )
    op.create_table('cancellation_request',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('appointment_id', sa.Uuid(), nullable=False),
    sa.Column('web_user_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'resolved', 'withdrawn', name='cancellationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['web_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['web_user_id'], ['web_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cancellation_notification_recipient',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cancellation_request_id', sa.Uuid(), nullable=False),
    sa.Column('web_user_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.Enum('auto_computed', 'preconfigured', 'both', name='notificationsource'), nullable=False),
    sa.ForeignKeyConstraint(['cancellation_request_id'], ['cancellation_request.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['web_user_id'], ['web_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cancellation_notification_recipient')
    op.drop_table('cancellation_request')
    op.drop_table('team_notification_settings')
    op.drop_table('location_notification_circle')
    op.drop_table('inbox_message')
    op.drop_table('project_settings')
    # ### end Alembic commands ###
