"""add_web_user_tables

Revision ID: b08a5ba1f4ff
Revises: 163d3b2a85cc
Create Date: 2026-03-23 14:51:19.001016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b08a5ba1f4ff'
down_revision: Union[str, Sequence[str], None] = '163d3b2a85cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('web_user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=254), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id')
    )
    op.create_index(op.f('ix_web_user_email'), 'web_user', ['email'], unique=True)
    op.create_table('web_user_role',
    sa.Column('web_user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'dispatcher', 'employee', 'accountant', name='webuserrole'), nullable=False),
    sa.ForeignKeyConstraint(['web_user_id'], ['web_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('web_user_id', 'role')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('web_user_role')
    op.drop_index(op.f('ix_web_user_email'), table_name='web_user')
    op.drop_table('web_user')
    # ### end Alembic commands ###
