"""add user_location_color

Revision ID: b328fdd08f2b
Revises: b4c5d6e7f8a9
Create Date: 2026-04-24 18:39:13.475025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b328fdd08f2b'
down_revision: Union[str, Sequence[str], None] = 'b4c5d6e7f8a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_location_color',
    sa.Column('web_user_id', sa.Uuid(), nullable=False),
    sa.Column('location_of_work_id', sa.Uuid(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=9), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_of_work_id'], ['location_of_work.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['web_user_id'], ['web_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('web_user_id', 'location_of_work_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_location_color')
    # ### end Alembic commands ###
