# weights for sat-solver objective:
WEIGHT_UNASSIGNED_SHIFTS = 100_000
WEIGHT_SUM_SQUARED_SHIFT_DEVIATIONS = 0.001
WEIGHT_CONSTRAINTS_WEIGHTS_IN_AVAIL_DAY_GROUPS = 1
WEIGHT_CONSTRAINTS_WEIGHTS_IN_EVENT_GROUPS = 1
