[minimization_weights]
unassigned_shifts = 100000.0
sum_squared_deviations = 0.005
constraints_weights_in_avail_day_groups = 1.0
constraints_weights_in_event_groups = 1.0
constraints_location_prefs = 0.001
constraints_partner_loc_prefs = 0.0001
constraints_fixed_casts_conflicts = 1000000000.0
constraints_cast_rule = 1000.0

[constraints_multipliers.sliders_location_prefs]
"0.0" = 100000000000000
"0.5" = 10
"1.0" = 0
"1.5" = -10
"2.0" = -20

[constraints_multipliers.sliders_partner_loc_prefs]
"0.0" = 20
"0.5" = 10
"1.0" = 0
"1.5" = -10
"2.0" = -20

[constraints_multipliers.sliders_levels_weights_event_groups]
"1.0" = 100
"2.0" = 10
"3.0" = 1

[constraints_multipliers.sliders_weights_avail_day_groups]
"0.0" = 1000
"1.0" = 0
"2.0" = -1

[constraints_multipliers.sliders_levels_weights_av_day_groups]
"1.0" = 1
"2.0" = 1
"3.0" = 1

[constraints_multipliers.partner_loc_prefs_levels]
